interface Assets {
  [key: string]: string;
}

export type AssetName =
  | "AWS"
  | "Bootstrap"
  | "C"
  | "Cpp"
  | "Celery"
  | "Django"
  | "FastApi"
  | "Flask"
  | "Go"
  | "Kafka"
  | "Neo4j"
  | "Nginx"
  | "Numpy"
  | "Pandas"
  | "RabbitMQ"
  | "Rust"
  | "Scrapy"
  | "Selenium"
  | "Docker"
  | "Csharp"
  | "Xamarin"
  | "TypeScript"
  | "VueJs"
  | "ReactJs"
  | "Dart"
  | "Kotlin"
  | "Python"
  | "NodeJs"
  | "Deno"
  | "Svelte"
  | "ExpressJs"
  | "JavaScript"
  | "Fastify"
  | "NestJs"
  | "Quasar"
  | "SolidJs"
  | "Electron"
  | "Flutter"
  | "Java"
  | "AdonisJs"
  | "Android"
  | "Angular"
  | "PostgreSQL"
  | "Firebase"
  | "Sass"
  | "Unknown"
  | "MongoDB"
  | "Redis"
  | "Tailwind"
  | "HTML"
  | "Premiere"
  | "Photoshop"
  | "CSS"
  | "AfterEffects"
  | "Illustrator"
  | "Nuxt"
  | "Vite"
  | "Vitest"
  | "Jest"
  | "Unocss"
  | "Ruvy"
  | "Postcss"
  | "Nextjs"
  | "Postgres"
  | "Stripe";

const assets: Assets = {
  AWS: "aws.svg",
  Bootstrap: "bootstrap.svg",
  C: "c.svg",
  Cpp: "cpp.svg",
  Celery: "celery.svg",
  Django: "django.svg",
  FastApi: "fastapi",
  Flask: "flask.svg",
  Go: "go.svg",
  Kafka: "kafka.svg",
  Neo4j: "neo4j.svg",
  Nginx: "nginx.svg",
  Numpy: "numpy.svg",
  Pandas: "pandas.svg",
  RabbitMQ: "rabbitmq.svg",
  Rust: "rust.svg",
  Scrapy: "scrapy.png",
  Selenium: "selenium.svg",
  Docker: "docker.svg",
  Csharp: "csharp.svg",
  Xamarin: "xamarin.svg",
  TypeScript: "ts.png",
  VueJs: "vue.png",
  ReactJs: "react.svg",
  Dart: "dart.png",
  Kotlin: "kotlin.png",
  Python: "python.png",
  NodeJs: "node.png",
  Deno: "deno.png",
  Svelte: "svelte.png",
  ExpressJs: "express.png",
  JavaScript: "js.png",
  Fastify: "fastify.svg",
  NestJs: "nest.svg",
  Quasar: "quasar.svg",
  SolidJs: "solid.svg",
  Electron: "electron.png",
  Flutter: "flutter.svg",
  Java: "java.png",
  AdonisJs: "adonis.png",
  Android: "android.png",
  Angular: "angular.png",
  PostgreSQL: "postgres.png",
  Firebase: "firebase.png",
  Sass: "sass.png",
  Unknown: "no-img.svg",
  MongoDB: "mongodb.svg",
  Redis: "redis.svg",
  Tailwind: "tailwind.svg",
  HTML: "html.svg",
  Premiere: "premiere.svg",
  Photoshop: "photoshop.svg",
  CSS: "css.svg",
  AfterEffects: "after-effects.svg",
  Illustrator: "illustrator.svg",
  Nuxt: "nuxt.png",
  Vite: "vite.png",
  Vitest: "vitest.svg",
  Jest: "jest.png",
  Unocss: "unocss.svg",
  Ruvy: "ruvy.svg",
  Postcss: "postcss.svg",
  Nextjs: "nextjs.svg",
  Postgres: "postgresql.svg",
  Stripe: "stripe.svg",
};

export function getAssets(name: AssetName) {
  return `${assets[name]}`;
}
